Ext.define('Module.Platform.Statistics.model.CouponTRModel', {
	extend : 'Ext.data.Model',
	
fields : ['tradeId',
          'tradeCode', 
          'inAccoutId', 
          'outAccoutId', 
          'applyTime', 
          'completeTime', 
          'money', 
          'payMoney',
          'tansMoney', 
          'busType', 
          'busDesc', 
          'payType', 
          'tradeStatus', 
          'opUserId',
          'opUserName',
          'frozenCode',
          'outTradeCode',
          'payWay', 
          'productNum', 
          'couponId',
          'couponName', 
          'billingType', 
          'serviceTime', 
          'moduleId', 
          'moduleName', 
          'moduleCode'
         ]
});