Ext.define('Module.Platform.Statistics.model.SMBTRModel', {
	extend : 'Ext.data.Model',
	
fields : ['tradeId',
          'tradeCode', 
          'inAccoutId', 
          'outAccoutId', 
          'applyTime', 
          'completeTime', 
          'money', 
          'payMoney',
          'tansMoney', 
          'busType', 
          'busDesc', 
          'payType', 
          'tradeStatus', 
          'opUserId',
          'opUserName',
          'frozenCode',
          'outTradeCode',
          'payWay', 
          'productNum', 
          'mbId',
          'mbName',
          'billingType', 
          'serviceTime', 
          'moduleId', 
          'moduleName', 
          'moduleCode', 
          'shopId', 
          'shopStatus', 
          'shopLogo', 
          'shopName', 
          'shopCode', 
          'appId', 
          'soId', 
          'contacts', 
          'phone', 
          'soUserId', 
          'ciId'
          ]
});